config/routes.rb
Rails.application.routes.draw do
  scope 'my' do
    devise_for :users, path: "", :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
    }
  end
  devise_scope :user do
    get 'user/:name' => 'users/registrations#show', as: :user
    get 'my' => 'users/registrations#my'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  post '/search'  => 'homes#search'
  get '/info'     => 'homes#info'
  get '/request'  => 'homes#request'
  scope 'info' do
    resources :coments, only:[:index,:create]
  end
  get '/autocomplete_games/:word' => 'games#autocomplete_games'
  get '/autocomplete_tags/:tags'  => 'tags#autocomplete_tags'

  resources :games, except:[:edit, :destroy], param: :name do
    resources :game_coments, only:[:index,:create]
    resources :coments, only:[:index,:create]
    resources :reviews, only:[:index,:new,:create]
    resource :game_favorites, only: [:create,:destroy]
  end
  resources :genres, only:[:index,:create,:update] do
    resources :coments, only:[:index,:create]
  end
  resources :machines, only:[:index,:create,:update] do
    resources :coments, only:[:index,:create]
  end
  resources :tags, only:[:index, :create, :destroy]

  #resources :users, only:[:show,:edit,:update]

  get '/admins'        => 'admins#top'
  get '/admins/search' => 'admins#search'
  get '/admins/reques'=> 'admins#reques'
  resource :admins, only:[:edit,:update,:destroy]
end

app/models/coment.rb
class Coment < ApplicationRecord

  has_ancestry

end

app/models/game.rb
class Game < ApplicationRecord

  def to_param
    name
  end

  has_many :game_favorites, dependent: :destroy
  has_many :game_coments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations
  has_many :machine_relations, dependent: :destroy
  has_many :machines, through: :machine_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations

  def tag_save(tag_list)
    current_tag_list = self.tags.pluck(:name) unless self.tags.nil?
    old = current_tag_list - tag_list
    new = tag_list - current_tag_list

    old.each do |name|
      self.tags.delete Tag.find_by(name: name)
    end

    new.each do |name|
      game_tag = Tag.find_or_create_by(name: name)
      self.tags << game_tag
    end
  end

  scope :title_autocomplete, ->(word) {
    where("name LIKE :q OR kana LIKE :q",q: "%#{word.tr('ぁ-ん','ァ-ン')}%").order(:name, :kana)
  }

  def favorited_by?(user)
    game_favorites.where(user_id: user.id).exists?
  end

end

app/models/game_coment.rb
class GameComent < ApplicationRecord
  belongs_to :game

  has_ancestry

end

app/models/game_favorite.rb
class GameFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :genre_relations, dependent: :destroy
  has_many :games, through: :genre_relations

end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/machine.rb
class Machine < ApplicationRecord

  has_many :machine_relations, dependent: :destroy
  has_many :games, through: :machine_relations

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  scope :search, -> (way,star){
    where("#{way}": star.to_i-0.9..star.to_i) if star.present?
  }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_relations, dependent: :destroy
  has_many :games, through: :tag_relations

  scope :tag_autocomplete, ->(word) {
    where("name LIKE :q",q: "%#{word.tr('ぁ-ん','ァ-ン')}%").order(:name)
  }

end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :game
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role:{ "一般会員": 1, "編集者": 2, "管理者": 3, "マスター": 5}

  def to_param
    name
  end

  has_many :game_favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true
  validates :birth, presence: true

  scope :search, ->(word) {
    where("name LIKE :q",q: "%#{word}%").order(:name)
  }

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/reques.html.erb
<h1>管理者用ページ</h1>
<%= form_with( model: @coment, url: coments_path, local: true) do |f| %>
  <div class="coment-form">
    <% if @coments.any? %>
      <ul>
        <% @coments.roots.last(10).each do |coment_root| %>
          <li>
            <%= f.radio_button :ancestry, coment_root.id %><%= coment_root.body %> -- <%= coment_root.name %> <%= coment_root.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
            <% if coment_root.present? && coment_root.has_children? %>
              <ul>
                <% coment_root.children.each do |coment_child| %>
                  <li>
                    <%= f.radio_button :ancestry, coment_child.id %><%= coment_child.body %> -- <%= coment_child.name %> <%= coment_child.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                    <% if coment_child.present? && coment_child.has_children? %>
                      <ul>
                        <% coment_child.children.each do |coment| %>
                          <li>
                            <%= coment.body %> -- <%= coment.name %> <%= coment.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                          </li>
                        <% end %>
                      </ul>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="mt-2 mb-5">
      <% user_name = user_signed_in? ? current_user.name : "" %>
      <%= f.radio_button :ancestry,"root", checked: true %>
      <%= f.text_field :name, placeholder: "名前",value: "#{user_name}", class:"coment-name" %>
      <%= f.text_field :body, placeholder: "コメント", class:"coment-body",autocomplete:"off" %>
      <%= f.hidden_field :page, value: request.path %>
      <%= f.submit "挿入" %>
    </div>
  </div>
<% end %>
<h3>ユーザー管理</h3>
<%= form_with url: admins_reques_path, method: :get, skip_enforcing_utf8: true, local: true do |f| %>
  <%= f.search_field :word, placeholder: "ユーザー名" %>
  <%= f.submit "検索" %>
<% end %>
<% if @users.present? %>
  <% @users.each do |user| %>
    <div><%= link_to user.name, admins_reques_path(name: user.name) %></div>
  <% end %>
<% end %>
<% if @user.present? %>
  <%= form_with model: @user, url: admins_path, local: true do |f| %>
    <div><%= @user.name %></div>
    <div>
      <%= f.hidden_field :id, value: @user.id %>
      <%= f.radio_button :role, User.roles.keys[@user.role_before_type_cast] %>
      <%= f.label User.roles.keys[@user.role_before_type_cast], for:"user_role_#{User.roles.keys[@user.role_before_type_cast]}" %>
      <%= f.radio_button :role, @user.role, checked: true %>
      <%= f.label @user.role, for:"user_role_#{@user.role}" %>
    </div>
    <%= f.submit "更新",name: "users" %>
  <% end %>
<% end %>

app/views/admins/top.html.erb
<h1>管理者ページ</h1>

<%= form_with( model: @coment, url: coments_path, local: true) do |f| %>
  <div class="coment-form">
    <% if @coments.any? %>
      <ul>
        <% @coments.roots.last(10).each do |coment_root| %>
          <li>
            <%= f.radio_button :ancestry, coment_root.id %><%= coment_root.body %> -- <%= coment_root.name %> <%= coment_root.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
            <% if coment_root.present? && coment_root.has_children? %>
              <ul>
                <% coment_root.children.each do |coment_child| %>
                  <li>
                    <%= f.radio_button :ancestry, coment_child.id %><%= coment_child.body %> -- <%= coment_child.name %> <%= coment_child.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                    <% if coment_child.present? && coment_child.has_children? %>
                      <ul>
                        <% coment_child.children.each do |coment| %>
                          <li>
                            <%= coment.body %> -- <%= coment.name %> <%= coment.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                          </li>
                        <% end %>
                      </ul>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="mt-2 mb-5">
      <% user_name = user_signed_in? ? current_user.name : "" %>
      <%= f.radio_button :ancestry,"root", checked: true %>
      <%= f.text_field :name, placeholder: "名前",value: "#{user_name}", class:"coment-name" %>
      <%= f.text_field :body, placeholder: "コメント", class:"coment-body",autocomplete:"off" %>
      <%= f.hidden_field :page, value: request.path %>
      <%= f.submit "挿入" %>
    </div>
  </div>
<% end %>
<h3>管理に携わりたい方はこちら</h3>
<div class="mt-2 mb-5">
  <%= form_with( model: @coment, url: coments_path, local: true) do |f| %>
    <% user_name = user_signed_in? ? current_user.name : "" %>
    <%= f.radio_button :ancestry,"root", checked: true %>
    <%= f.text_field :name, placeholder: "名前",value: "#{user_name}", class:"coment-name" %>
    <%= f.text_field :body, placeholder: "コメント", class:"coment-body",autocomplete:"off" %>
    <%= f.hidden_field :page, value: "/admins/reques" %>
    <%= f.submit "挿入" %>
  <% end %>
</div>

app/views/layouts/_side.html.erb
<!--<h1>サイドバー</h1>-->
<% s_genres = Genre.eager_load(:games).all %>
<% s_machines = Machine.joins(:machine_relations).group(:machine_id).order('count(game_id) desc').limit(10) %>
<% s_tags = Tag.joins(:tag_relations).group(:tag_id).order('count(game_id) desc').limit(10) %>

<table class="side-table">
  <tr>
    <th>
      <h3>ゲームを探す</h3>
      <div class="text-align-right mb-2">
        <div class="search-form mb-1">
          <%= form_with url: games_path, method: :get, skip_enforcing_utf8: true, local: true do |f| %>
            <%= f.search_field :word, placeholder: "ゲームタイトル", class:"autocomplete-title" %>
            <%= f.submit "検索",name: "title" %>
          <% end %>
        </div>
         <% if user_signed_in? && current_user.role_before_type_cast >= 2 %>
          <%= link_to "ゲームの登録", new_game_path %> ｜
        <% end %>
        <%= link_to "詳細検索", games_path %>
      </div>
    </th>
  </tr>
  <tr>
    <td>
      <p>ジャンル</p>
      <div>
        <% s_genres.each do |genre| %>
          <div>
            <%= link_to "#{genre.name}(#{genre.games.size})" ,games_path(commit: "検索",genre_ids: genre.id) %>
          </div>
        <% end %>
      </div>
      <div class="text-align-right" ><%= link_to "詳細", genres_path %></div>
    </td>
  </tr>
  <tr>
    <td>
      <p>機種</p>
      <div>
        <% s_machines.each_with_index do |machine, i| %>
          <% break if i >= 10 %>
          <div>
            <%= link_to "#{machine.name}(#{machine.games.size})" ,games_path(commit: "検索",machine_ids: machine.id) %>
          </div>
        <% end %>
      </div>
      <div class="text-align-right" ><%= link_to "詳細", machines_path %></div>
    </td>
  </tr>
  <tr>
    <td>
      <p>タグ</p>
      <div>
        <% s_tags.each do |tag| %>
          <div>
            <%= link_to "#{tag.name}(#{tag.games.size})" ,games_path(commit: "検索",tags: tag.name) %>
          </div>
        <% end %>
      </div>
      <div class="text-align-right" ><%= link_to "一覧", tags_path %></div>
    </td>
  </tr>
  <%  if user_signed_in? && current_user.role_before_type_cast >= 3 %>
    <tr>
      <td>
        <p>管理</p>
        <div><%= link_to "トップページ", admins_path %></div>
        <div><%= link_to "管理者用", admins_reques_path if user_signed_in? && current_user.role_before_type_cast >= 3 %></div>
      </td>
    </tr>
  <% end %>
  <!--<tr>-->
  <!--  <td>-->
  <!--    <p>最新の10件</p>-->
  <!--  </td>-->
  <!--</tr>-->
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <header class="flex justify-content-space-between">
      <div>
        <%= link_to "トップ", root_path %>
      </div>
      <div>
        <% if user_signed_in? %>
          <%= link_to "info" , info_path %>
          <%= link_to "マイページ" , my_path %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "info" , info_path %>
          <%= link_to 'アカウント登録', new_user_registration_path %>
          <%= link_to 'ログイン', user_session_path %>
        <% end %>
      </div>
      <!--<div class="search-form">-->
      <!--  <%#= form_with url: search_path, skip_enforcing_utf8: true, local: true  do |f| %>-->
      <!--    <%#= f.search_field :word, placeholder: "サイト内検索" %>-->
      <!--    <%#= f.submit "検索",name: nil %>-->
      <!--  <%# end %>-->
      <!--</div>-->
    </header>

    <main class="flex">
      <div class="side">
        <%= render "layouts/side" %>
      </div>
      <div class="main">
        <%= yield %>
      </div>
    </main>

    <footer>
    </footer>
  </body>
</html>