config/routes.rb
Rails.application.routes.draw do
  scope 'my' do
    devise_for :users, path: "", :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
    }
  end
  devise_scope :user do
    get 'user/:name' => 'users/registrations#show', as: :user
    get 'my' => 'users/registrations#my'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  post '/search'  => 'homes#search'
  get '/info'     => 'homes#info'
  get '/request'  => 'homes#request'
  scope 'info' do
    resources :coments, only:[:index,:create]
  end
  get '/autocomplete_games/:word' => 'games#autocomplete_games'
  get '/autocomplete_tags/:tags'  => 'tags#autocomplete_tags'

  resources :games, except:[:edit, :destroy], param: :name do
    resources :game_coments, only:[:index,:create]
    resources :coments, only:[:index,:create]
    resources :reviews, only:[:index,:new,:create]
    resource :game_favorites, only: [:create,:destroy]
  end
  resources :genres, only:[:index,:create,:update] do
    resources :coments, only:[:index,:create]
  end
  resources :machines, only:[:index,:create,:update] do
    resources :coments, only:[:index,:create]
  end
  resources :tags, only:[:index, :create, :destroy]

  #resources :users, only:[:show,:edit,:update]

  get '/admins'        => 'admins#top'
  get '/admins/search' => 'admins#search'
  get '/admins/reques'=> 'admins#reques'
  resource :admins, only:[:edit,:update,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord

  has_ancestry

end

app/models/game.rb
class Game < ApplicationRecord

  def to_param
    name
  end

  has_many :game_favorites, dependent: :destroy
  has_many :game_coments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations
  has_many :machine_relations, dependent: :destroy
  has_many :machines, through: :machine_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations

  def tag_save(tag_list)
    current_tag_list = self.tags.pluck(:name) unless self.tags.nil?
    old = current_tag_list - tag_list
    new = tag_list - current_tag_list

    old.each do |name|
      self.tags.delete Tag.find_by(name: name)
    end

    new.each do |name|
      game_tag = Tag.find_or_create_by(name: name)
      self.tags << game_tag
    end
  end

  scope :title_autocomplete, ->(word) {
    where("name LIKE :q OR kana LIKE :q",q: "%#{word.tr('ぁ-ん','ァ-ン')}%").order(:name, :kana)
  }

  def favorited_by?(user)
    game_favorites.where(user_id: user.id).exists?
  end

end

app/models/game_coment.rb
class GameComent < ApplicationRecord
  belongs_to :game

  has_ancestry

end

app/models/game_favorite.rb
class GameFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :genre_relations, dependent: :destroy
  has_many :games, through: :genre_relations

end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/machine.rb
class Machine < ApplicationRecord

  has_many :machine_relations, dependent: :destroy
  has_many :games, through: :machine_relations

end

app/models/machine_relation.rb
class MachineRelation < ApplicationRecord
  belongs_to :game
  belongs_to :machine
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  scope :search, -> (way,star){
    where("#{way}": star.to_i-0.9..star.to_i) if star.present?
  }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_relations, dependent: :destroy
  has_many :games, through: :tag_relations

  scope :tag_autocomplete, ->(word) {
    where("name LIKE :q",q: "%#{word.tr('ぁ-ん','ァ-ン')}%").order(:name)
  }

end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :game
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role:{ "一般会員": 1, "編集者": 2, "管理者": 3, "マスター": 5}

  def to_param
    name
  end

  has_many :game_favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true
  validates :birth, presence: true

  scope :search, ->(word) {
    where("name LIKE :q",q: "%#{word}%").order(:name)
  }

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  # ログイン済ユーザーのみにアクセスを許可する
  before_action :authenticate_user!, except:[:index,:show,:autocomplete_games]

  def new
    @game = Game.new
    @genres = Genre.all
  end

  def create
    @game = Game.new(game_params)
    tag_list = params[:game][:tag_name].split
    if @game.save
      @game.tag_save(tag_list)
      redirect_to game_path(@game.name)
    else
      render new
    end
  end

  def index
    if params[:commit].present?
      @word = params[:word]
      @notword = params[:notword]
      @tags = params[:tags]
      @genres = params[:genre_ids]
      @machines = params[:machine_ids]
      @games = search(@word,@notword,@tags,@genres,@machines).page(params[:page]).per(15)
    elsif params[:title].present?
      @word = params[:word]
      @games = Game.eager_load(:genres, :machines, :tags)
      if @word.present?
        words = @word.split(/[[:blank:]]+/).select(&:present?)
        words.each do |word|
          @games = @games.where("games.name like :q OR kana like :q ", q: "%#{word}%").page(params[:page]).per(15)
        end
      end
    else
        @games = Game.eager_load(:genres, :machines, :tags).page(params[:page]).per(15)
    end
  end

  def show
    @game = Game.preload(:genres, :machines, :tags, :game_favorites, :reviews, :game_coments).find_by(name: params[:name])
    @tag = Tag.new
    @reviews = @game.reviews.last(5)
    @game_coment = GameComent.new
    @coment = Coment.new
  end

  def update
    @game = Game.find_by(name: params[:name])
    if @game.update(game_params)
      redirect_to game_path(@game.name)
    else
      render show
    end
  end

  def search(word,notword,tag,genres,machines)
    items = Game.includes(:genres, :machines, :tags).references(:genres, :machines, :tags)

    items = items.where(id: MachineRelation.select(:game_id).where(machine_id: machines).group(:game_id).having("COUNT(DISTINCT machine_relations.machine_id) = ?", machines.size)) if machines.present?
    items = items.where(id: GenreRelation.select(:game_id).where(genre_id: genres).group(:game_id).having("COUNT(DISTINCT genre_relations.genre_id) = ?", genres.size)) if genres.present?

    if tag.present?
      tags = tag.split(/[[:blank:]]+/)
      tags_id = Tag.where(name: tags).ids
      items = items.where(id: TagRelation.select(:game_id).where(tag_id: tags_id).group(:game_id).having("COUNT(DISTINCT tag_relations.tag_id) = ?", tags_id.size))
    end

    if word.present?
      words = word.split(/[[:blank:]]+/).select(&:present?)
      words.each do |word|
        tags_id = Tag.where("name like ?", "%#{word}%").ids
        items = items.where("games.name like :q OR kana like :q OR games.body like :q", q: "%#{word}%").or(items.where(id: TagRelation.select(:game_id).where(tag_id: tags_id).group(:game_id)))
      end
    end
    if notword.present?
      notwords = notword.split(/[[:blank:]]+/).select(&:present?)
      notwords.each do |word|
        tags_id = Tag.where("name like ?", "%#{word}%").ids
        items = items.where.not("games.name like :q OR kana like :q OR games.body like :q", q: "%#{word}%").where.not(id: TagRelation.select(:game_id).where(tag_id: tags_id).group(:game_id))
      end
    end

    return items
  end

  def autocomplete_games
    gamestitle = Game.title_autocomplete(params[:word]).pluck(:name).reject(&:blank?)
    render json: gamestitle
  end

private

  def game_params
    params.require(:game).permit(:name, :kana, :body, :cero, :official, :wiki, :day, genre_ids: [], machine_ids: [])
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1>ゲーム検索</h1>
<div class="search-area mb-2">
  <%= form_with url: games_path, method: :get, skip_enforcing_utf8: true, local: true do |f| %>
    <div>
      <label>キーワード検索</label>
      <%= f.search_field :word, value: @word, class:"autocomplete-title" %>
    </div>
    <div>
      <label>除外キーワード</label>
      <%= f.search_field :notword, value: @notword %>
    </div>
    <div class="CloseUp">
        <p>条件で絞り込む</p>
      <div>
        <label>タグ名</label>
        <%= f.search_field :tags, value: @tags, class:"autocomplete-tag" %>
      </div>
      <div>
        <label>ジャンル</label><br>
        <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_hidden: false, checked: @genres %>
      </div>
      <div>
        <label>機種</label><br>
        <%= f.collection_check_boxes :machine_ids, Machine.all, :id, :name, include_hidden: false, checked: @machines %>
      </div>
    </div>
    <%= f.submit "検索" %>
  <% end %>
</div>
<%= link_to "ゲームの登録", new_game_path if user_signed_in? && current_user.role_before_type_cast >= 1 %>
<div>
  <% if params[:title].present? %>
    <span><%= @word %>を含むゲームのタイトルが<%= @games.size %>件見つかりました</span>
  <% elsif params[:commit].present? %>
    <span>検索条件を満たしたゲームが<%= @games.size %>件見つかりました</span>
  <% end %>
</div>
<% @games.each do |game| %>
<table class="w-100 table  table-between-border">
  <tr>
    <th width="33%" class="text-align-left">
      <%= link_to game.name, game_path(game.name), class:"a-underline" %>
    </th>
    <td style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width: 0" colspan="2">
      <%= game.body %>
    </td>
  </tr>
  <tr>
    <td><% game.genres.each do |genre| %>
      <%= genre.name %>
    <% end %></td>
    <td><% game.machines.each do |machine| %>
      <%= machine.name %>
    <% end %></td>
    <td width="33%"><% game.tags.each do |tag| %>
      <%= tag.name %>
    <% end %></td>
  </tr>
</table>
<%= paginate(@games) %>
<% end %>

app/views/games/new.html.erb
<h1>ゲーム投稿</h1>
<div>
  <span>ゲームの登録で重複を防ぐため読み仮名の入力をお願いします。また省略せずに入力してください</span><br>
  <span>✖：ドラクエ(どらくえ) &emsp;〇：Dragon Quest(ドラゴンクエスト)</span>

</div>
<%= form_with model: @game do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "ゲームタイトル", class:"autocomplete-title"%>
    <%= f.text_field :kana, placeholder: "ゲームタイトル(読み仮名)", class:"autocomplete-title" %>
  </div>
  <div>
    <%= f.text_area :body, placeholder: "ゲーム概要", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
  </div>
  <div>
    <%= f.label "ジャンル：" %>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_hidden: false %>
  </div>
  <div>
    <%= f.label "機種：" %>
    <%= f.collection_check_boxes :machine_ids, Machine.all, :id, :name, include_hidden: false %>
  </div>
  <div>
    <%= f.text_field :tag_name, placeholder:"タグ", class:"autocomplete-tag" %><span class=tagkome>※単語を空白で区切ると一度に複数のタグを登録できます。</span>
  </div>
  <div>
    <%= f.text_field :cero, placeholder: "対象年齢" %>
  </div>
  <div>
    <%= f.text_area :official, placeholder: "公式サイト", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
  </div>
  <div>
    <%= f.text_area :wiki, placeholder: "攻略サイト", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
  </div>
  <div>
    <%= f.text_field :day, placeholder: "発売日" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<h1>ゲーム詳細</h1>
<% if params[:edit] == "true" %>
  <%= form_with model: @game, local: true do |f| %>
    <div>
      <%= f.text_field :name, placeholder: "ゲームタイトル" %>
      <%= f.text_field :kana, placeholder: "ゲームタイトル(かな)" %>
    </div>
    <div>
      <%= f.text_area :body, placeholder: "ゲーム概要", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
    </div>
    <div>
      <%= f.label "ジャンル：" %>
      <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_hidden: false %>
    </div>
    <div>
      <%= f.label "機種：" %>
      <%= f.collection_check_boxes :machine_ids, Machine.all, :id, :name, include_hidden: false %>
    </div>
    <div>
      <%= f.text_field :cero, placeholder: "対象年齢" %>
    </div>
    <div>
      <%= f.text_area :official, placeholder: "公式サイト", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
    </div>
    <div>
      <%= f.text_area :wiki, placeholder: "攻略サイト", oninput: "textAreaHeightSet(this)", onchange: "textAreaHeightSet(this)", class:"text_area" %>
    </div>
    <div>
      <%= f.text_field :day, placeholder: "発売日" %>
    </div>
    <%= f.submit %>
  <% end %>
<% else %>
  <table class="w-100 table table-border table-oddline-back">
    <tr>
      <td class="table-mini">
        ゲームタイトル
        <%= link_to "https://www.google.co.jp/search?q=#{@game.name}", target: :_blank, rel: "noopener noreferrer", class:"balloon-base" do %><i class="fas fa-search font-blue"></i><span class="balloon">ゲームタイトルでGoogle検索</span><% end %>
        <div id="favorite<%= @game.id %>"><%= render 'game_favorites/favo', game: @game %></div>
      </td>
      <td colspan="3"><%= @game.name %><br>(<%= @game.kana %>)</td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td class="w-40">
        <% @game.genres.each do |g| %>
          <%= g.name %>&nbsp;
        <% end %>
      </td>
      <td>機種</td>
      <td>
        <% @game.machines.each do |g| %>
          <%= g.name %>&nbsp;
        <% end %>
      </td>
    </tr>
    <tr>
      <td>対象年齢</td>
      <td><%= @game.cero %></td>
      <td class="w-10">発売日</td>
      <td><%= @game.day %></td>
    </tr>
   <tr>
      <td>公式サイト</td>
      <td colspan="3">
        <% @game.official.split(/\R/).each do |url| %>
          <%= link_to url ,url, target: :_blank, rel: "noopener noreferrer" %><br>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>攻略サイト</td>
      <td colspan="3">
        <% @game.wiki.split(/\R/).each do |url| %>
          <%= link_to url ,url, target: :_blank, rel: "noopener noreferrer" %><br>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="text-align-right">
    <%  if user_signed_in? && current_user.role_before_type_cast >= 2 %>
    <%= link_to "編集", game_path(@game.name, edit: true) %>
    <% else %>
    <div style="height:1.5em;"></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= $unique %><%= $unique = "" %>
    <div class="TagForm pr-2">
      <button type="button" class="TagEdit" >タグ編集</button>
      <button type="button" class="TagEdit" hidden>編集完了</button>
    </div>
    <div class="TagForm">
      <div id="Tag"><%= render "tags/tag", game: @game %></div>
      <div class="TagInput mt-1" >
        <%= form_with model: @game, url: tags_path, method: :post do |f| %>
          <%= f.hidden_field :id, value: @game.id %>
          <%= f.text_field :tag_name, class:"autocomplete-tag", id:"TagInput" %>
          <%= f.submit "登録" %><span class=tagkome style="margin-left: 40px">※単語を空白で区切ると一度に複数のタグを登録できます。</span>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <div>ゲーム概要</div>
    <div style="white-space:pre-wrap" class="ml-2"><%= @game.body %></div>
  </div>

<% end %>

<h3>新着レビュー</h3>
<div>
  <%= link_to "レビュー一覧", game_reviews_path(game_name: @game.name) %>
  <%  if user_signed_in? && current_user.role_before_type_cast >= 1 %>
    ｜ <%= link_to "レビュー投稿", new_game_review_path(game_name: @game.name) %>
  <% end %>
</div>
<% @reviews.each do |review| %>
  <table class="ml-1 review-table table-between-border">
    <tr>
      <td width="40%">
        <div><%= link_to review.user.name, user_path(review.user.name) %></div>
        <div>プレイ時間：<%= review.hour %></div>
      </td>
      <td><div id="story-rate-<%= review.id %>"></div></td>
        <script>
          $('#story-rate-<%= review.id %>').empty();
          $('#story-rate-<%= review.id %>').html("<span>ストーリー</span>");
          $('#story-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.story %>,
          });
          $('#story-rate-<%= review.id %> img').wrapAll("<div class=\"flex flex-wrap-nowrap\">")
        </script>
      <td><div id="system-rate-<%= review.id %>"></div></td>
        <script>
          $('#system-rate-<%= review.id %>').empty();
          $('#system-rate-<%= review.id %>').html("<span>操作・システム</span>")
          $('#system-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.system %>,
          });
          $('#system-rate-<%= review.id %> img').wrapAll("<div class=\"flex flex-wrap-nowrap\">")
        </script>
      <td><div id="total-rate-<%= review.id %>"></div></td>
        <script>
          $('#total-rate-<%= review.id %>').empty();
          $('#total-rate-<%= review.id %>').html("<span>総合</span>");
          $('#total-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.total %>,
          });
          $('#total-rate-<%= review.id %> img').wrapAll("<div class=\"flex flex-wrap-nowrap\">")
        </script>
    </tr>
    <tr>
      <% if review.is_spoiler? %>
        <td colspan="4" class="pt-1 pb-1 pl-1">
          <input type="button" id="button<%= review.id %>" value="ネタバレを含みます">
          <span id="hidden<%= review.id %>"></span>
          <script>
            $("#button<%= review.id %>").click(function(){
              $("#hidden<%= review.id %>").replaceWith('<span id="hidden<%= review.id %>" style="white-space:pre-wrap" ><%= review.body.gsub(/\R/, '\n') %></span>');
              $("#button<%= review.id %>").remove();
            });
          </script>
        </td>
      <% else %>
        <td colspan="4" style="white-space:pre-wrap" class="pt-1 pb-1 pl-1"><%= review.body %></td>
      <% end %>
      </tr>
  </table>
<% end %>
<h3>コメント</h3><%= link_to "コメント一覧", game_game_coments_path(game_name: @game.name) %>
<%= form_with( model: [@game, @game_coment], url: game_game_coments_path(game_name: @game.name), local: true) do |f| %>
  <div class="coment-form">
    <% if @game.game_coments.any? %>
      <ul>
        <% @game.game_coments.roots.last(10).each do |coment_root| %>
          <li>
            <%= f.radio_button :ancestry, coment_root.id %><%= coment_root.body %> -- <%= coment_root.name %> <%= coment_root.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
            <% if coment_root.present? && coment_root.has_children? %>
              <ul>
                <% coment_root.children.each do |coment_child| %>
                  <li>
                    <%= f.radio_button :ancestry, coment_child.id %><%= coment_child.body %> -- <%= coment_child.name %> <%= coment_child.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                    <% if coment_child.present? && coment_child.has_children? %>
                      <ul>
                        <% coment_child.children.each do |coment| %>
                          <li>
                            <%= coment.body %> -- <%= coment.name %> <%= coment.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                          </li>
                        <% end %>
                      </ul>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="mt-2 mb-5">
      <% user_name = user_signed_in? ? current_user.name : "" %>
      <%= f.radio_button :ancestry,"root", checked: true %>
      <%= f.text_field :name, placeholder: "名前",value: "#{user_name}", class:"coment-name" %>
      <%= f.text_field :body, placeholder: "コメント", class:"coment-body",autocomplete:"off" %>
      <%= f.submit "挿入" %>
    </div>
  </div>
<% end %>